vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: "%kernel.project_dir%/public/images/articles"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: app.directory_namer.article
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
